configs = {
    "CartPole-v1": {
        "load_run": None,
        "played_frames": 0,
        "max_frames": 3000000,
        "sample_reuse": 2,
        "per_experience_replay": True,
        "per_buffer_size": 5000000,
        "per_min_frames": 1000000,
        "per_priority_exponent": 0.9,
        "update_frequency": 1,
        "num_envs": 256,
        "batch_size": 16,
        "sequence_length": 100,
        "bootstrap_length": 100,
        "d_push": 50,
        "d_pull": 50,
        "d_target": 1000,
        "discount": 0.995,
        "reward_scaling_1": 0.25,
        "reward_scaling_2": 0.25,
        "v_loss_scaling": 1.0,
        "q_loss_scaling": 1.0,
        "p_loss_scaling": 1.0,
        "c_clip": 1.05,
        "rho_clip": 1.05,
        "lr_finder": False,
        "learning_rate": 1e-3,
        "warmup_steps": 4000,
        "adamw_beta1": 0.9,
        "adamw_beta2": 0.98,
        "adamw_epsilon": 1e-6,
        "adamw_clip_norm": 1e10,
        "weight_decay_rate": 0.01,
        "architecture_params": {
            "architecture": "dense",
            "input_dim": 4,
            "hidden_dim": 128,
            "action_dim": 2},
        "bandit_params": {
            "mode": ["argmax", "random"],
            "tau1": [0.0, 50.0],
            "tau2": [0.0, 50.0],
            "epsilon": [0.0, 1.0],
            "acc": [50, 50, 10],
            "acc2": [2, 3, 4],
            "width": [2, 3, 4],
            "lr": [0.05, 0.1, 0.2],
            "d": 3}
    },
    "LunarLander-v2": {
        "load_run": None,
        "played_frames": 0,
        "max_frames": 10000000,
        "sample_reuse": 2,
        "per_experience_replay": True,
        "per_buffer_size": 5000000,
        "per_min_frames": 1000000,
        "per_priority_exponent": 0.9,
        "update_frequency": 1,
        "num_envs": 256,
        "batch_size": 16,
        "sequence_length": 80,
        "bootstrap_length": 80,
        "d_push": 20,
        "d_pull": 20,
        "d_target": 1000,
        "discount": 0.997,
        "reward_scaling_1": 0.4,
        "reward_scaling_2": 0.3,
        "v_loss_scaling": 1.0,
        "q_loss_scaling": 2.0,
        "p_loss_scaling": 2.0,
        "c_clip": 1.05,
        "rho_clip": 1.05,
        "lr_finder": False,
        "learning_rate": 5e-6,
        "warmup_steps": 4000,
        "adamw_beta1": 0.9,
        "adamw_beta2": 0.98,
        "adamw_epsilon": 1e-6,
        "adamw_clip_norm": 1e10,
        "weight_decay_rate": 0.01,
        "architecture_params": {
            "architecture": "dense",
            "input_dim": 8,
            "hidden_dim": 256,
            "action_dim": 4},
        "bandit_params": {
            "mode": ["argmax", "random"],
            "tau1": [0.0, 50.0],
            "tau2": [0.0, 50.0],
            "epsilon": [0.0, 1.0],
            "acc": [50, 50, 10],
            "acc2": [2, 3, 4],
            "width": [2, 3, 4],
            "lr": [0.05, 0.1, 0.2],
            "d": 3}
    },
    "LaserHockey-v0": {
        "load_run": None,
        "played_frames": 0,
        "max_frames": 10000000,
        "sample_reuse": 2,
        "per_experience_replay": True,
        "per_buffer_size": 5000000,
        "per_min_frames": 1000000,
        "per_priority_exponent": 0.9,
        "update_frequency": 1,
        "num_envs": 256,
        "batch_size": 64,
        "sequence_length": 20,
        "bootstrap_length": 5,
        "d_push": 20,
        "d_pull": 20,
        "d_target": 1000,
        "discount": 0.99,
        "reward_scaling_1": 2,
        "reward_scaling_2": 10,
        "v_loss_scaling": 1.0,
        "q_loss_scaling": 14.0,
        "p_loss_scaling": 14.0,
        "c_clip": 1.05,
        "rho_clip": 1.05,
        "lr_finder": False,
        "learning_rate": 1e-4,
        "warmup_steps": 4000,
        "weight_decay_rate": 0.01,
        "adamw_beta1": 0.9,
        "adamw_beta2": 0.98,
        "adamw_clip_norm": 1e10,
        "adamw_epsilon": 1e-4,
        "architecture_params": {
            "architecture": "dense",
            "input_dim": 16,
            "hidden_dim": 256,
            "action_dim": 27},
        "bandit_params": {
            "mode": ["argmax", "random"],
            "tau1": [0.0, 50.0],
            "tau2": [0.0, 50.0],
            "epsilon": [0.0, 1.0],
            "acc": [50, 50, 10],
            "acc2": [2, 3, 4],
            "width": [2, 3, 4],
            "lr": [0.05, 0.1, 0.2],
            "d": 3}
    },
    "Crypto-v0": {
        # Add hyperparameters for Crypto-v0 environment here
    }
}